name: Package AutoSubs for Windows
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout AutoSubs Repo Code
      uses: actions/checkout@v4
        
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 23
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
      
    - name: Install Dependencies
      run: |
        cd AutoSubs-App
        npm install

    - name: Bundle Tauri App
      run: |
        cd AutoSubs-App
        npm run tauri build

    - name: Package Python Server
      run: |
        cd Mac-Server
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pyinstaller transcription-server.spec --noconfirm
        deactivate

    - name: Move Python Server and App to Output Folder
      run: |
        mv "AutoSubs-App/src-tauri/target/release/bundle/macos/AutoSubs.app" "Output"
        mv "Mac-Server/dist/Transcription-Server" "Output"

    - name: Get Latest Release Tag
      id: get_latest_release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

    - name: Upload Asset to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.LATEST_TAG }}
        files: AutoSubs-Installer-Mac-ARM.pkg
        token: ${{ secrets.GH_TOKEN }}